### ISSUE TITLE
Border and Bossbar does not work

### ISSUE THREAD

**Issue by jassper0** [LunarBreaker/LunarBreakerAPI2#3]

**Comment by jassper0** [comment]
Also the Team Markers disappear after 64 blocks (server's player render distance)

**Comment by cProxi** [comment]
Honestly not sure if Lunar Client has support for Borders or Bossbars anymore. Team markers will disappear after the server's render distance due to the client not being able to get their location. Not sure if there's a workaround for this.

Let me know if you experience any other issues, or have any other questions.

- Callum // ProPractice

**Comment by jassper0** [comment]
There is a way around. The lastMs input, is put into use when the player is super far way, so it updates in ticks. Do you think it has to do with the posMap you did in TeamHandler, its just 0.0D.

**Comment by jassper0** [comment]
I know what the problem is. In the posMap, when the first packet is sent, it keeps that location and doesn't up anything else. I did a runnable to keep updating the HashMap with the players' newest coordinates.

**Comment by jassper0** [comment]
I don't know much Java but if you find a better way of updating the Coordinates(Location) in the HashMap. I found out that TeamPackets has to be sent every second or something. I don't know if its optimized that way but its the only method that i found that works.

**Comment by cProxi** [comment]
I may make the API do this automatically at some point. But for now the best way to achieve this is to make a runnable. Reuse the same Teammates variable. Each time the task runs, make it send the players that Teammates using `LunarBreakerAPI.getInstance.getTeammateHandler().sendTeammates(Player player, Teammates teammates)`. Play around with it a bit, if you have any issues with this let me know. Sorry I don't have time at the moment to test this myself.

- Callum // ProPractice
